version: "3.7"

services: 
  backend:
    container_name: fiserver
    restart: always
    build:
      context: .
      target: development
    command: yarn start:dev
    # volumes:
    #   - ./src:/var/www/fiserver/src
    #   - ./test:/var/www/fiserver/test
    # working_dir: /fiserver/
    ports: 
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9020:9020
    env_file:
      - .env
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    networks:
      - fiserver
  
  postgres:
    container_name: fidatabase
    restart: always
    image: "postgres"
    networks:
      - fiserver
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PG_DATA: /var/lib/postgres/data
    ports: 
      - '${DB_PORT}:5432' 
    volumes: 
      - pgdata:/var/lib/postgres/data
  
  redis: 
    container_name: firedis
    restart: always
    image: redis:6.0-alpine
    ports:
      - 6379:6379
    networks:
      - fiserver
    expose:
      - "3011"
    volumes:
      - firedis_data:/data

volumes:
  pgdata:
  firedis_data:

networks:
  fiserver:
  


  
  

